import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { experiences } from '@/data/experiences';
import { useExperiences } from '@/context/ExperienceContext';

export default function DetailScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const item = experiences.find((experience) => experience.id === id) ?? experiences[0]; const { savedIds, toggleSaved, itineraryIds, addToItinerary } = useExperiences(); const saved = savedIds.includes(item.id); const planned = itineraryIds.includes(item.id);
  return <View style={[styles.screen, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={styles.imageWrap}><Image source={item.image} contentFit="cover" style={styles.image} /><LinearGradient colors={['rgba(4,10,19,0.1)', 'rgba(4,10,19,0.92)']} style={StyleSheet.absoluteFill} /><View style={[styles.actions, { top: insets.top + 10 }]}><Pressable onPress={() => router.back()} style={styles.circle}><Ionicons name="arrow-back" size={20} color="#F5F0E8" /></Pressable><Pressable onPress={() => toggleSaved(item.id)} style={styles.circle}><Ionicons name={saved ? 'heart' : 'heart-outline'} size={20} color={saved ? colors.primary : '#F5F0E8'} /></Pressable></View><View style={styles.imageCopy}><Text style={[styles.detailTag, { color: item.accent }]}>{item.category.toUpperCase()} · DUBAI</Text><Text style={styles.detailTitle}>{item.title}</Text><Text style={styles.detailSubtitle}>{item.subtitle}</Text></View></View><View style={styles.body}><View style={styles.metaRow}><View style={styles.meta}><Ionicons name="location-outline" size={17} color={colors.primary} /><Text style={[styles.metaText, { color: colors.foreground }]}>{item.location}</Text></View><View style={styles.meta}><Ionicons name="star" size={15} color={colors.primary} /><Text style={[styles.metaText, { color: colors.foreground }]}>{item.rating} rating</Text></View></View><Text style={[styles.copy, { color: colors.mutedForeground }]}>Make room for the kind of moment that stays with you. This carefully chosen Dubai experience pairs beautiful surroundings with the details that turn a visit into a story worth retelling.</Text><View style={[styles.info, { backgroundColor: colors.secondary }]}><View><Text style={[styles.infoLabel, { color: colors.mutedForeground }]}>STARTING FROM</Text><Text style={[styles.price, { color: colors.foreground }]}>{item.price}</Text></View><Text style={[styles.availability, { color: colors.primary }]}>Available today</Text></View><Pressable onPress={() => addToItinerary(item.id)} style={[styles.cta, { backgroundColor: colors.primary }]}><Ionicons name={planned ? 'checkmark-circle' : 'add-circle-outline'} size={20} color={colors.primaryForeground} /><Text style={[styles.ctaText, { color: colors.primaryForeground }]}>{planned ? 'Added to your itinerary' : 'Add to my itinerary'}</Text></Pressable><Text style={[styles.sectionTitle, { color: colors.foreground }]}>A little more magic</Text><View style={styles.featureRow}>{['Curated by locals', 'Flexible planning', 'Dubai, beautifully'].map((label, index) => <View key={label} style={styles.feature}><Ionicons name={index === 0 ? 'sparkles-outline' : index === 1 ? 'time-outline' : 'sunny-outline'} size={18} color={colors.primary} /><Text style={[styles.featureText, { color: colors.foreground }]}>{label}</Text></View>)}</View></View></ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, scroll: { paddingBottom: 40 }, imageWrap: { height: 475 }, image: { ...StyleSheet.absoluteFillObject }, actions: { position: 'absolute', left: 18, right: 18, flexDirection: 'row', justifyContent: 'space-between' }, circle: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(7,18,31,0.65)', alignItems: 'center', justifyContent: 'center' }, imageCopy: { position: 'absolute', left: 22, right: 22, bottom: 25 }, detailTag: { fontSize: 10, fontWeight: '800', letterSpacing: 1.6, marginBottom: 9 }, detailTitle: { color: '#F5F0E8', fontSize: 35, fontWeight: '700', letterSpacing: -1 }, detailSubtitle: { color: 'rgba(245,240,232,0.72)', fontSize: 13, marginTop: 5 }, body: { padding: 22 }, metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 }, meta: { flexDirection: 'row', alignItems: 'center', gap: 7 }, metaText: { fontSize: 12, fontWeight: '600' }, copy: { fontSize: 14, lineHeight: 22 }, info: { borderRadius: 16, padding: 15, marginTop: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, infoLabel: { fontSize: 9, letterSpacing: 1.2, fontWeight: '700' }, price: { fontSize: 17, fontWeight: '700', marginTop: 5 }, availability: { fontSize: 11, fontWeight: '700' }, cta: { height: 56, borderRadius: 17, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginTop: 13 }, ctaText: { fontSize: 13, fontWeight: '800' }, sectionTitle: { fontSize: 19, fontWeight: '700', marginTop: 31, marginBottom: 14 }, featureRow: { flexDirection: 'row', justifyContent: 'space-between' }, feature: { alignItems: 'center', gap: 7, flex: 1 }, featureText: { fontSize: 10, textAlign: 'center' } });