import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useExperiences } from '@/context/ExperienceContext';
import { useAuth, useUser } from '@clerk/expo';

export default function ProfileScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { savedIds, itineraryIds } = useExperiences();
  const { isSignedIn, signOut } = useAuth();
  const { user } = useUser();
  const rows = [{ icon: 'heart-outline' as const, label: 'Saved places', value: `${savedIds.length}` }, { icon: 'map-outline' as const, label: 'My itineraries', value: `${itineraryIds.length}` }, { icon: 'notifications-outline' as const, label: 'Travel updates', value: 'On' }, { icon: 'settings-outline' as const, label: 'Settings', value: '' }];
  const displayName = user?.firstName || user?.primaryEmailAddress?.emailAddress?.split('@')[0] || 'Dubai explorer';
  return <View style={[styles.screen, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 15, paddingBottom: Platform.OS === 'web' ? 105 : 112 }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>YOUR DUBAI</Text><View style={styles.profileTop}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={[styles.avatarText, { color: colors.primaryForeground }]}>{displayName.slice(0, 1).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{isSignedIn ? displayName : 'Your Dubai profile'}</Text><Text style={[styles.member, { color: colors.mutedForeground }]}>{isSignedIn ? 'Explorer · Dubai curious' : 'Sign in to keep your Dubai close'}</Text></View>{isSignedIn ? <Pressable onPress={() => signOut()}><Text style={[styles.signOut, { color: colors.primary }]}>Sign out</Text></Pressable> : null}</View>{!isSignedIn ? <Pressable onPress={() => router.push('/auth')} style={[styles.signIn, { backgroundColor: colors.primary }]}><Text style={[styles.signInText, { color: colors.primaryForeground }]}>Sign in or create account</Text><Ionicons name="arrow-forward" size={18} color={colors.primaryForeground} /></Pressable> : null}<View style={[styles.note, { borderColor: colors.border }]}><Ionicons name="sparkles-outline" size={18} color={colors.primary} /><Text style={[styles.noteText, { color: colors.foreground }]}>Your next extraordinary moment is closer than you think.</Text></View><Text style={[styles.section, { color: colors.foreground }]}>Your space</Text>{rows.map((row) => <Pressable key={row.label} onPress={() => row.label === 'Saved places' && router.push('/saved')} style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.rowIcon, { backgroundColor: colors.secondary }]}><Ionicons name={row.icon} size={19} color={colors.primary} /></View><Text style={[styles.rowLabel, { color: colors.foreground }]}>{row.label}</Text>{row.value ? <Text style={[styles.rowValue, { color: colors.mutedForeground }]}>{row.value}</Text> : null}<Ionicons name="chevron-forward" size={17} color={colors.mutedForeground} /></Pressable>)}<Text style={[styles.section, { color: colors.foreground, marginTop: 30 }]}>For businesses</Text><Pressable style={[styles.business, { backgroundColor: colors.secondary }]}><View style={{ flex: 1 }}><Text style={[styles.businessTitle, { color: colors.foreground }]}>Put your business on the map.</Text><Text style={[styles.businessText, { color: colors.mutedForeground }]}>Reach the people already dreaming about Dubai.</Text></View><Ionicons name="arrow-forward" size={20} color={colors.primary} /></Pressable></ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20 }, eyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 2 }, profileTop: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 23, marginBottom: 23 }, avatar: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 23, fontWeight: '800' }, name: { fontSize: 23, fontWeight: '700' }, member: { fontSize: 12, marginTop: 4 }, signOut: { fontSize: 12, fontWeight: '700' }, signIn: { borderRadius: 15, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }, signInText: { fontSize: 14, fontWeight: '800' }, note: { padding: 15, borderRadius: 17, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 10 }, noteText: { fontSize: 12, lineHeight: 18, flex: 1 }, section: { fontSize: 17, fontWeight: '700', marginTop: 30, marginBottom: 10 }, row: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1 }, rowIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowLabel: { flex: 1, fontSize: 14, fontWeight: '500' }, rowValue: { fontSize: 12, marginRight: 6 }, business: { borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, businessTitle: { fontSize: 14, fontWeight: '700' }, businessText: { fontSize: 11, lineHeight: 16, marginTop: 4 }, });