import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { ExperienceCard } from '@/components/ExperienceCard';
import { experiences } from '@/data/experiences';
import { useExperiences } from '@/context/ExperienceContext';

export default function SavedScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { savedIds, itineraryIds, toggleSaved, removeFromItinerary } = useExperiences();
  const saved = experiences.filter((item) => savedIds.includes(item.id)); const itinerary = experiences.filter((item) => itineraryIds.includes(item.id));
  return <View style={[styles.screen, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 15, paddingBottom: Platform.OS === 'web' ? 105 : 112 }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>YOUR CITY EDIT</Text><Text style={[styles.title, { color: colors.foreground }]}>Saved for later.</Text><View style={[styles.plan, { backgroundColor: colors.secondary }]}><View style={[styles.planIcon, { backgroundColor: colors.primary }]}><Ionicons name="sparkles" size={20} color={colors.primaryForeground} /></View><View style={{ flex: 1 }}><Text style={[styles.planTitle, { color: colors.foreground }]}>{itinerary.length} stops in your itinerary</Text><Text style={[styles.planText, { color: colors.mutedForeground }]}>A little more Dubai, one beautiful day at a time.</Text></View></View><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>My itinerary</Text><Text style={[styles.count, { color: colors.primary }]}>{itinerary.length} PLACES</Text></View>{itinerary.map((item, index) => <View key={item.id} style={[styles.stop, { borderBottomColor: colors.border }]}><View style={[styles.number, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: '800', fontSize: 12 }}>{index + 1}</Text></View><View style={{ flex: 1 }}><Text style={[styles.stopTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.stopMeta, { color: colors.mutedForeground }]}>{item.location} · {item.category}</Text></View><Pressable onPress={() => removeFromItinerary(item.id)} hitSlop={10}><Ionicons name="close" size={18} color={colors.mutedForeground} /></Pressable></View>)}<View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Saved places</Text><Text style={[styles.count, { color: colors.primary }]}>{saved.length} SAVED</Text></View>{saved.map((item) => <ExperienceCard key={item.id} item={item} compact saved={savedIds.includes(item.id)} onPress={() => router.push({ pathname: '/detail', params: { id: item.id } })} onSave={() => toggleSaved(item.id)} />)}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20 }, eyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 2 }, title: { fontSize: 29, fontWeight: '700', letterSpacing: -1, marginTop: 5 }, plan: { borderRadius: 19, padding: 15, flexDirection: 'row', gap: 12, alignItems: 'center', marginTop: 22 }, planIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, planTitle: { fontSize: 14, fontWeight: '700' }, planText: { fontSize: 11, marginTop: 4 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 28, marginBottom: 13 }, sectionTitle: { fontSize: 20, fontWeight: '700' }, count: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, stop: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1 }, number: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, stopTitle: { fontSize: 14, fontWeight: '600' }, stopMeta: { fontSize: 11, marginTop: 4 } });